/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../node_modules/ionic-angular/components/spinner/spinner.ngfactory';
import * as import2 from 'ionic-angular/components/spinner/spinner';
import * as import3 from 'ionic-angular/config/config';
import * as import4 from '@angular/common';
import * as import5 from '../../../src/components/img-loader';
import * as import6 from '../../../src/providers/image-loader';
import * as import7 from '../../../src/providers/image-loader-config';
import * as import8 from '@ionic-native/file/index';
const styles_ImgLoader:any[] = ['ion-spinner[_ngcontent-%COMP%] { float: none; margin-left: auto; margin-right: auto; display: block; }'];
export const RenderType_ImgLoader:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 0,
  styles: styles_ImgLoader,
  data: {}
}
);
function View_ImgLoader_1(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
      (l()(),import0.ɵeld(0,(null as any),(null as any),1,'ion-spinner',([] as any[]),[[
        2,
        'spinner-paused',
        (null as any)
      ]
    ],(null as any),(null as any),import1.View_Spinner_0,import1.RenderType_Spinner)),
    import0.ɵdid(114688,(null as any),0,import2.Spinner,[
      import3.Config,
      import0.ElementRef,
      import0.Renderer
    ]
    ,{
      color: [
        0,
        'color'
      ]
      ,
      name: [
        1,
        'name'
      ]

    }
    ,(null as any))
  ]
  ,(ck,v) => {
    var co:any = v.component;
    const currVal_1:any = co.spinnerColor;
    const currVal_2:any = co.spinnerName;
    ck(v,1,0,currVal_1,currVal_2);
  },(ck,v) => {
    const currVal_0:any = import0.ɵnov(v,1)._paused;
    ck(v,0,0,currVal_0);
  });
}
export function View_ImgLoader_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵand(16777216,(null as any),(null as any),1,(null as any),View_ImgLoader_1)),
    import0.ɵdid(16384,(null as any),0,import4.NgIf,[
      import0.ViewContainerRef,
      import0.TemplateRef
    ]
      ,{ngIf: [
        0,
        'ngIf'
      ]
    },(null as any))
  ]
  ,(ck,v) => {
    var co:import5.ImgLoader = v.component;
    const currVal_0:any = ((co.spinner && co.isLoading) && !co.fallbackAsPlaceholder);
    ck(v,1,0,currVal_0);
  },(null as any));
}
function View_ImgLoader_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'img-loader',([] as any[]),(null as any),(null as any),(null as any),View_ImgLoader_0,RenderType_ImgLoader)),
    import0.ɵdid(114688,(null as any),0,import5.ImgLoader,[
      import0.ElementRef,
      import0.Renderer,
      import6.ImageLoader,
      import7.ImageLoaderConfig,
      import8.File
    ]
    ,(null as any),(null as any))
  ]
  ,(ck,v) => {
    ck(v,1,0);
  },(null as any));
}
export const ImgLoaderNgFactory:import0.ComponentFactory<import5.ImgLoader> = import0.ɵccf('img-loader',import5.ImgLoader,View_ImgLoader_Host_0,{
  src: 'src',
  fallbackUrl: 'fallback',
  spinner: 'spinner',
  fallbackAsPlaceholder: 'fallbackAsPlaceholder',
  useImg: 'useImg',
  noCache: 'noCache',
  cache: 'cache',
  width: 'width',
  height: 'height',
  display: 'display',
  backgroundSize: 'backgroundSize',
  backgroundRepeat: 'backgroundRepeat',
  spinnerName: 'spinnerName',
  spinnerColor: 'spinnerColor'
}
,{load: 'load'},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2xlb2Nob2kvRG9jdW1lbnRzL1Byb2plY3RzL2lvbmljLWltYWdlLWxvYWRlci9zcmMvY29tcG9uZW50cy9pbWctbG9hZGVyLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1VzZXJzL2xlb2Nob2kvRG9jdW1lbnRzL1Byb2plY3RzL2lvbmljLWltYWdlLWxvYWRlci9zcmMvY29tcG9uZW50cy9pbWctbG9hZGVyLnRzIiwibmc6Ly8vVXNlcnMvbGVvY2hvaS9Eb2N1bWVudHMvUHJvamVjdHMvaW9uaWMtaW1hZ2UtbG9hZGVyL3NyYy9jb21wb25lbnRzL2ltZy1sb2FkZXIudHMuSW1nTG9hZGVyLmh0bWwiLCJuZzovLy9Vc2Vycy9sZW9jaG9pL0RvY3VtZW50cy9Qcm9qZWN0cy9pb25pYy1pbWFnZS1sb2FkZXIvc3JjL2NvbXBvbmVudHMvaW1nLWxvYWRlci50cy5JbWdMb2FkZXJfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8aW9uLXNwaW5uZXIgKm5nSWY9XCJzcGlubmVyICYmIGlzTG9hZGluZyAmJiAhZmFsbGJhY2tBc1BsYWNlaG9sZGVyXCIgW25hbWVdPVwic3Bpbm5lck5hbWVcIiBbY29sb3JdPVwic3Bpbm5lckNvbG9yXCI+PC9pb24tc3Bpbm5lcj4iLCI8aW1nLWxvYWRlcj48L2ltZy1sb2FkZXI+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7TUNBQTtRQUFBO1FBQUE7UUFBQTtNQUFBO0lBQUE7Z0JBQUE7Ozs7SUFBQTtLQUFBO01BQUE7UUFBQTtRQUFBO01BQUE7O01BQUE7UUFBQTtRQUFBO01BQUE7O0lBQUE7S0FBQTs7OztJQUF5RjtJQUFyQjtJQUFwRSxTQUF5RixVQUFyQixTQUFwRTs7SUFBQTtJQUFBLFNBQUEsU0FBQTs7Ozs7SUFBQTtnQkFBQTs7O0lBQUE7T0FBQTtRQUFBO1FBQUE7TUFBQTtJQUFBOzs7O0lBQWE7SUFBYixTQUFhLFNBQWI7Ozs7O0lDQUE7Z0JBQUE7Ozs7OztJQUFBO0tBQUE7OztJQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
